SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `management_hotel` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `management_hotel` ;
CREATE TABLE IF NOT EXISTS `management_hotel`.`admin` (
  `ID` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS `management_hotel`.`room` (
  `id_room` VARCHAR(10) NOT NULL,
  `nameroom` VARCHAR(255) NOT NULL,
  `numbed` INT NOT NULL,
  `description` TEXT NULL,
  `price` FLOAT NOT NULL,
  `admin_ID` INT NOT NULL,
  PRIMARY KEY (`id_room`, `admin_ID`),
  INDEX `fk_room_admin_idx` (`admin_ID` ASC) VISIBLE,
  CONSTRAINT `fk_room_admin`
    FOREIGN KEY (`admin_ID`)
    REFERENCES `management_hotel`.`admin` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


